// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Singleton pattern to prevent multiple client instances
let supabaseInstance: SupabaseClient<Database> | null = null;

const createSupabaseClient = (): SupabaseClient<Database> => {
  if (supabaseInstance) {
    return supabaseInstance;
  }

  if (!isSupabaseConfigured) {
    console.error('Supabase config missing: set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY)');
  }

  supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
      storageKey: 'pericia-automata-auth'
    }
  });

  const hardSignOut = async () => {
    try {
      await supabaseInstance?.auth.signOut();

      const keysToRemove: string[] = [];
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key && (key.includes('supabase') || key.includes('auth') || key.includes('sb-'))) {
          keysToRemove.push(key);
        }
      }
      keysToRemove.forEach((key) => localStorage.removeItem(key));
      sessionStorage.clear();
    } catch {
    } finally {
      window.location.href = '/';
    }
  };

  supabaseInstance.auth.onAuthStateChange(async (event) => {
    if (event === 'SIGNED_OUT') {
      await hardSignOut();
    }
  });

  return supabaseInstance;
};

// Export the singleton instance
export const supabase = createSupabaseClient();

// Função para limpar sessão corrompida completamente
export const clearCorruptedSession = async () => {
  try {
    console.log('Clearing corrupted session...');
    
    // Sign out from Supabase
    await supabase.auth.signOut();
    
    // Clear all auth-related items from localStorage
    const keysToRemove = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && (key.includes('supabase') || key.includes('auth') || key.includes('sb-'))) {
        keysToRemove.push(key);
      }
    }
    
    keysToRemove.forEach(key => localStorage.removeItem(key));
    
    // Clear session storage as well
    sessionStorage.clear();
    
    console.log('Session cleared, redirecting to login...');
    
    // Redirect to login page
    window.location.href = '/';
    
  } catch (error) {
    console.error('Erro ao limpar sessão:', error);
    // Force reload as fallback
    window.location.reload();
  }
};

// Função para verificar e recuperar sessão
export const validateAndRecoverSession = async () => {
  try {
    const { data: { session }, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error('Session validation error:', error);
      const msg = String((error as any)?.message || '').toLowerCase();
      if (msg.includes('refresh_token_not_found') || msg.includes('invalid refresh token')) {
        await clearCorruptedSession();
        return null;
      }
    }
    
    return session;
  } catch (error) {
    console.error('Session recovery error:', error);
    await clearCorruptedSession();
    return null;
  }
};

// Função para obter usuário autenticado com validação
export const getAuthenticatedUser = async () => {
  try {
    const session = await validateAndRecoverSession();
    if (!session) {
      return null;
    }

    const { data: { user }, error } = await supabase.auth.getUser();
    
    if (error) {
      console.error('Get user error:', error);
      if (error.message.includes('JWT') || error.message.includes('token')) {
        await clearCorruptedSession();
        return null;
      }
    }
    
    return user;
  } catch (error) {
    console.error('Authentication error:', error);
    await clearCorruptedSession();
    return null;
  }
};
